language: generic

sudo: required

services:
 - docker

env:
  matrix:
    - DOCKERFILE=fedora SHARED=ON METIS_INT64=OFF
    - DOCKERFILE=fedora SHARED=ON METIS_INT64=ON
    - DOCKERFILE=ubuntu SHARED=ON METIS_INT64=OFF
    - DOCKERFILE=ubuntu SHARED=ON METIS_INT64=ON

script:
  - docker build -t flecsi/flecsi_tpl:${DOCKERFILE}
                 -f dockerfiles/${DOCKERFILE} dockerfiles/
                 --build-arg SHARED={SHARED}
                 --build-arg METIS_INT64=${METIS_INT64}

# TODO: push created Docker image to DockerHub
# - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
# - docker push flecsi/flecsi_tpl:${DOCKERFILE}

