language: generic

sudo: required

services:
 - docker

env:
  matrix:
    - DOCKERFILE=fedora SHARED=ON METIS_INT64=OFF
    - DOCKERFILE=fedora SHARED=ON METIS_INT64=ON
    - DOCKERFILE=fedora SHARED=ON METIS_INT64=ON DOCKERHUB=true
    - DOCKERFILE=ubuntu SHARED=ON METIS_INT64=OFF
    - DOCKERFILE=ubuntu SHARED=ON METIS_INT64=ON
    - DOCKERFILE=ubuntu SHARED=ON METIS_INT64=ON DOCKERHUB=true

script:
  - docker build --build-arg SHARED=${SHARED}
                 --build-arg METIS_INT64=${METIS_INT64}
                 --build-arg DOCKERHUB=${DOCKERHUB}
                 --build-arg TRAVIS=${TRAVIS}
                 --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
                 --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
                 --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
                 --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 --build-arg TRAVIS_TAG=${TRAVIS_TAG}
                 -t flecsi/flecsi_tpl:${DOCKERFILE}
                 -f dockerfiles/${DOCKERFILE} dockerfiles/
                 

after_success:
  - if [[ ${DOCKERHUB} =true && ${DOCKER_EMAIL} && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} ]]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push flecsi/flecsi_tpl:${DOCKERFILE};
   fi

