language: generic

sudo: required

services:
 - docker

env:
  matrix:
    - DOCKERFILE=fedora
    - DOCKERFILE=ubuntu
#    - SHARED=OFF
#    - SHARED=ON

script:
  - docker build -t flecsi/flecsi_tpl:${DOCKERFILE}
                 -f dockerfile/${DOCKERFILE} docker/

#  - mkdir build && cd build && cmake -DBUILD_SHARED_LIBS="${SHARED}" -DENABLE_EXODUS=ON -DENABLE_LAPACK=ON -DENABLE_METIS=ON -DENABLE_SCOTCH=ON -DENABLE_ZLIB=ON -DCMAKE_INSTALL_PREFIX=$HOME/tpl .. && make -j2 && cd ..


compiler:
  - gcc
